const themeFiles = [
  "Active4D.json",
  "All Hallows Eve.json",
  "Amy.json",
  "Birds of Paradise.json",
  "Blackboard.json",
  "Brilliance Black.json",
  "Brilliance Dull.json",
  "Chrome DevTools.json",
  "Clouds Midnight.json",
  "Clouds.json",
  "Cobalt.json",
  "Cobalt2.json",
  "Dawn.json",
  "Dominion Day.json",
  "Dracula.json",
  "Dreamweaver.json",
  "Eiffel.json",
  "Espresso Libre.json",
  "GitHub Dark.json",
  "GitHub Light.json",
  "GitHub.json",
  "IDLE.json",
  "idleFingers.json",
  "iPlastic.json",
  "Katzenmilch.json",
  "krTheme.json",
  "Kuroir Theme.json",
  "LAZY.json",
  "MagicWB (Amiga).json",
  "Merbivore Soft.json",
  "Merbivore.json",
  "monoindustrial.json",
  "Monokai Bright.json",
  "Monokai.json",
  "Night Owl.json",
  "Nord.json",
  "Oceanic Next.json",
  "Pastels on Dark.json",
  "Slush and Poppies.json",
  "Solarized-dark.json",
  "Solarized-light.json",
  "SpaceCadet.json",
  "Sunburst.json",
  "Textmate (Mac Classic).json",
  "themelist.json",
  "Tomorrow-Night-Blue.json",
  "Tomorrow-Night-Bright.json",
  "Tomorrow-Night-Eighties.json",
  "Tomorrow-Night.json",
  "Tomorrow.json",
  "Twilight.json",
  "Upstream Sunburst.json",
  "Vibrant Ink.json",
  "Xcode_default.json",
  "Zenburnesque.json",
];

export default themeFiles;
